from bs4 import BeautifulSoup
import requests

list = ["acfifjfajpekbmhmjppnmmjgmhjkildl",
"agnoocojkneiphkobpcfoaenhpjnmifb",
"akdgnmcogleenhbclghghlkkdndkjdjc",
"baocaagndhipibgklemoalmkljaimfdj",
"begphfmcgdepfkoofbpkfcnimdeocadd",
"bfbameneiokkgbdmiekhjnmfkcnldhhm",
"bhlhnicpbhignbdhedgjhgdocnmhomnp",
"bjogjfinolnhfhkbipphpdlldadpnmhc",
"bkpenclhmiealbebdopglffmfdiilejc",
"bmdblncegkenkacieihfhpjfppoconhi",
"dcngeagmmhegagicpcmpinaoklddcgon",
"djcfdncoelnlbldjfhinnjlhdjlikmph",
"dogkpdfcklifaemcdfbildhcofnopogp",
"eelojgpfkmhiikmhkineneemcahoehjo",
"elicpjhcidhpjomhibiffojpinpmmpil",
"fdpohaocaechififmbbbbbknoalclacl",
"fhbjgbiflinjbdggehcddcbncdddomop",
"fmkadmapgofadopljbjfkapdkoienihi",
"fpkknkljclfencbdbgkenhalefipecmb",
"gbmdgpbipfallnflgajpaliibnhdgobh",
"gighmmpiobklfepjocnamgkkbiglidom",
"iabeihobmhlgpkcgjiloemdbofjbdcic",
"iahamcpedabephpcgkeikbclmaljebjp",
"Iaiioopjkcekapmldfgbebdclcnpgnlo",
"iegkaadihdhfjcllhcpkfjflfcfhoopf",
"ifooldnmmcmlbdennkpdnlnbgbmfalko",
"innpjfdalfhpcoinfnehdnbkglpmogdi",
"ioalpmibngobedobkmbhgmadaphocjdn",
"ipkjmjaledkapilfdigkgfmpekpfnkih",
"ippoiefadonbimjgjlijphdkdgbagigp",
"jbbplnpkjmmeebjpijfedlgcdilocofh",
"jnkmfdileelhofjcijamephohjechhna",
"kejbdjndbnbjgmefkgdddjlbokphdefk",
"kkelicaakdanhinjdeammmilcgefonfh",
"kmdldgcmokdpmacblnehppgkjphcbpnn",
"lhdoppojpmngadmnindnejefpokejbdd",
"lkmofgnohbedopheiphabfhfjgkhfcgf",
"lmhkpmbekcpmknklioeibfkpmmfibljd",
"mcdcbjjoakogbcopinefncmkcamnfkdb",
"nlipoenfbbikpbjkfpfillcgkoblgpmj",
"ocdmogmohccmeicdhlhhgepeaijenapj",
"ohlencieiipommannpdfcmfdpjjmeolj",
"paijfdbeoenhembfhkhllainmocckace",
"eekilpcjjofgpnogedhneoepbbgnnpjb",
"jjeeggmbnhckmgdhmgdckeigabjfbddl",
"kmicfegjejpginnockfnjpdgeffebdcf",
"efcfolpjihicnikpmhnmphjhhpiclljc",
"plnahcmalebffmaghcpcmpaciebdhgdf",
"dlknooajieciikpedpldejhhijacnbda",
"fdgfkebogiimcoedlicjlajpkdmockpc",
"offljimabadkdnhijlbopjlkaolpdgip",
"mbopgmdnpcbohhpnfglgohlbhfongabi",
"acfifjfajpekbmhmjppnmmjgmhjkildl",
"jjoehgfmpefldljiipnmgnfmcbfjkaad",
"bcellnicpceplkigjnldelfglfmomhon",
"pcpmcffcomlcjgpcheokdfcjipanjdpc",
"inkgahcdacjcejipadnndepfllmbgoag",
"pkdeeppnbfkpocpkikgceigjpdfpdhfa",
"dcngeagmmhegagicpcmpinaoklddcgon",
"cpgoncheakfjhldfbebekijoeaabnfeb",
"jjoehgfmpefldljiipnmgnfmcbfjkaad",
"blkboeaihdlecgdjjgkcabbacndbjibc",
"hcclkhcbkkdkaedoogloknhdbkjjgdem",
"gjedkhmeelbomjafdlehdcomjhobcnbk",
"ooonkoejkmhiacbhhkdgfeemioceapbh",
"gifgpciglhhpmeefjdmlpboipkibhbjg",
"jjpdebaihkangkfpbgefmnnlafkahebn",
"ngfbofmmhadhjnlodckfafckdhmlcpeh",
"oghajcjpbolpfoikoccffglngkphjgbo",
"plmndhfiofdlcgahoinehedbincopilm",
"bhdplaindhdkiflmbfbciehdccfhegci",
"chgajipdilbjolpgafadpdggjaeeapic",
"dhikfimimcjpoaliefjlffaebdeomeni",
"cdnapgfjopgaggbmfgbiinmmbdcglnam",
"bjnkkhimoaclnddigpphpgkfgeggokam",
"elgalmkoelokbchhkhacckoklkejnhcd",
"dbepggeogbaibhgnhhndojpepiihcmeb",
"blipmdconlkpinefehnmjammfjpmpbjk",
"pekljbkpgnpphbkgjbfgiiclemodfpen",
"njcdgcofcbnlbpkpdhmlmiblaglnkpnj",
"kgjfgplpablkjnlkjmjdecgdpfankdle",]

with open('extensoes_chrome.txt', "a") as out:
    out.write("URL|NOME_DA_EXTENSAO|DESCRICAO_EXTENSAO")
    for i in list:
        page = requests.get("https://chrome.google.com/webstore/detail/"+i, verify=False)
        soup = BeautifulSoup(page.content, 'html.parser')
        out.write(str("https://chrome.google.com/webstore/detail/"+i)+"|"+str(soup.title.string)+"|"+str(soup.find(attrs={'name':'Description'}))+"\n")
